(package "csharp-mode"
         "1.1.1"
         "C# mode derived mode")

(website-url "https://github.com/emacs-csharp/csharp-mode")
(keywords "c#" "languages" "oop" "mode")

(package-file "csharp-mode.el")

(source "gnu")
(source "melpa")

(depends-on "emacs" "26.1")

(development
 (depends-on "assess")
 (depends-on "m-buffer"))

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
